//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\C\antlr4\HyTek\HyTek.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HyTekParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IHyTekListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInit([NotNull] HyTekParser.InitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInit([NotNull] HyTekParser.InitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.event"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvent([NotNull] HyTekParser.EventContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.event"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvent([NotNull] HyTekParser.EventContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.eventInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventInfo([NotNull] HyTekParser.EventInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.eventInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventInfo([NotNull] HyTekParser.EventInfoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.eventGender"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventGender([NotNull] HyTekParser.EventGenderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.eventGender"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventGender([NotNull] HyTekParser.EventGenderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.eventName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventName([NotNull] HyTekParser.EventNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.eventName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventName([NotNull] HyTekParser.EventNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.columnHeadersf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumnHeadersf([NotNull] HyTekParser.ColumnHeadersfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.columnHeadersf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumnHeadersf([NotNull] HyTekParser.ColumnHeadersfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.eventResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventResult([NotNull] HyTekParser.EventResultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.eventResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventResult([NotNull] HyTekParser.EventResultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.individualResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndividualResult([NotNull] HyTekParser.IndividualResultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.individualResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndividualResult([NotNull] HyTekParser.IndividualResultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.throwawayResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrowawayResult([NotNull] HyTekParser.ThrowawayResultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.throwawayResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrowawayResult([NotNull] HyTekParser.ThrowawayResultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.trials"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrials([NotNull] HyTekParser.TrialsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.trials"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrials([NotNull] HyTekParser.TrialsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.heightResults"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeightResults([NotNull] HyTekParser.HeightResultsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.heightResults"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeightResults([NotNull] HyTekParser.HeightResultsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.relayResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelayResult([NotNull] HyTekParser.RelayResultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.relayResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelayResult([NotNull] HyTekParser.RelayResultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.metric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetric([NotNull] HyTekParser.MetricContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.metric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetric([NotNull] HyTekParser.MetricContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.wind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWind([NotNull] HyTekParser.WindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.wind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWind([NotNull] HyTekParser.WindContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.legInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLegInfo([NotNull] HyTekParser.LegInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.legInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLegInfo([NotNull] HyTekParser.LegInfoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.leg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeg([NotNull] HyTekParser.LegContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.leg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeg([NotNull] HyTekParser.LegContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.legNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLegNumber([NotNull] HyTekParser.LegNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.legNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLegNumber([NotNull] HyTekParser.LegNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.place"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlace([NotNull] HyTekParser.PlaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.place"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlace([NotNull] HyTekParser.PlaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.jerseyNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJerseyNumber([NotNull] HyTekParser.JerseyNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.jerseyNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJerseyNumber([NotNull] HyTekParser.JerseyNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.athleteName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAthleteName([NotNull] HyTekParser.AthleteNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.athleteName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAthleteName([NotNull] HyTekParser.AthleteNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.athleteYear"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAthleteYear([NotNull] HyTekParser.AthleteYearContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.athleteYear"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAthleteYear([NotNull] HyTekParser.AthleteYearContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.schoolName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSchoolName([NotNull] HyTekParser.SchoolNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.schoolName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSchoolName([NotNull] HyTekParser.SchoolNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.seed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeed([NotNull] HyTekParser.SeedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.seed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeed([NotNull] HyTekParser.SeedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTime([NotNull] HyTekParser.TimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTime([NotNull] HyTekParser.TimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.distance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDistance([NotNull] HyTekParser.DistanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.distance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDistance([NotNull] HyTekParser.DistanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.dq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDq([NotNull] HyTekParser.DqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.dq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDq([NotNull] HyTekParser.DqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.dqReason"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDqReason([NotNull] HyTekParser.DqReasonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.dqReason"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDqReason([NotNull] HyTekParser.DqReasonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.performance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPerformance([NotNull] HyTekParser.PerformanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.performance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPerformance([NotNull] HyTekParser.PerformanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.heatNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeatNumber([NotNull] HyTekParser.HeatNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.heatNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeatNumber([NotNull] HyTekParser.HeatNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.points"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPoints([NotNull] HyTekParser.PointsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.points"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPoints([NotNull] HyTekParser.PointsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.tiebreaker"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTiebreaker([NotNull] HyTekParser.TiebreakerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.tiebreaker"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTiebreaker([NotNull] HyTekParser.TiebreakerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.hour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHour([NotNull] HyTekParser.HourContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.hour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHour([NotNull] HyTekParser.HourContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.minute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinute([NotNull] HyTekParser.MinuteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.minute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinute([NotNull] HyTekParser.MinuteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.second"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecond([NotNull] HyTekParser.SecondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.second"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecond([NotNull] HyTekParser.SecondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal([NotNull] HyTekParser.DecimalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal([NotNull] HyTekParser.DecimalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.period"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPeriod([NotNull] HyTekParser.PeriodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.period"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPeriod([NotNull] HyTekParser.PeriodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.day"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDay([NotNull] HyTekParser.DayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.day"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDay([NotNull] HyTekParser.DayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.month"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMonth([NotNull] HyTekParser.MonthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.month"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMonth([NotNull] HyTekParser.MonthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.year"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYear([NotNull] HyTekParser.YearContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.year"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYear([NotNull] HyTekParser.YearContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDate([NotNull] HyTekParser.DateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDate([NotNull] HyTekParser.DateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.clockTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClockTime([NotNull] HyTekParser.ClockTimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.clockTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClockTime([NotNull] HyTekParser.ClockTimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.foot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFoot([NotNull] HyTekParser.FootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.foot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFoot([NotNull] HyTekParser.FootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.inch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInch([NotNull] HyTekParser.InchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.inch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInch([NotNull] HyTekParser.InchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] HyTekParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] HyTekParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.words"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWords([NotNull] HyTekParser.WordsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.words"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWords([NotNull] HyTekParser.WordsContext context);
}
