//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\C\antlr4\HyTek\HyTek.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IHyTekListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class HyTekBaseListener : IHyTekListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit([NotNull] HyTekParser.InitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit([NotNull] HyTekParser.InitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.event"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvent([NotNull] HyTekParser.EventContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.event"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvent([NotNull] HyTekParser.EventContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.eventInfo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventInfo([NotNull] HyTekParser.EventInfoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.eventInfo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventInfo([NotNull] HyTekParser.EventInfoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.eventGender"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventGender([NotNull] HyTekParser.EventGenderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.eventGender"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventGender([NotNull] HyTekParser.EventGenderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.eventName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventName([NotNull] HyTekParser.EventNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.eventName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventName([NotNull] HyTekParser.EventNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.columnHeadersf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumnHeadersf([NotNull] HyTekParser.ColumnHeadersfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.columnHeadersf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumnHeadersf([NotNull] HyTekParser.ColumnHeadersfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.eventResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventResult([NotNull] HyTekParser.EventResultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.eventResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventResult([NotNull] HyTekParser.EventResultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.individualResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndividualResult([NotNull] HyTekParser.IndividualResultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.individualResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndividualResult([NotNull] HyTekParser.IndividualResultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.throwawayResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThrowawayResult([NotNull] HyTekParser.ThrowawayResultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.throwawayResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThrowawayResult([NotNull] HyTekParser.ThrowawayResultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.trials"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrials([NotNull] HyTekParser.TrialsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.trials"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrials([NotNull] HyTekParser.TrialsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.heightResults"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeightResults([NotNull] HyTekParser.HeightResultsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.heightResults"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeightResults([NotNull] HyTekParser.HeightResultsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.relayResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelayResult([NotNull] HyTekParser.RelayResultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.relayResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelayResult([NotNull] HyTekParser.RelayResultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.metric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetric([NotNull] HyTekParser.MetricContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.metric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetric([NotNull] HyTekParser.MetricContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.wind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWind([NotNull] HyTekParser.WindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.wind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWind([NotNull] HyTekParser.WindContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.legInfo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLegInfo([NotNull] HyTekParser.LegInfoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.legInfo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLegInfo([NotNull] HyTekParser.LegInfoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.leg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeg([NotNull] HyTekParser.LegContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.leg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeg([NotNull] HyTekParser.LegContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.legNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLegNumber([NotNull] HyTekParser.LegNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.legNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLegNumber([NotNull] HyTekParser.LegNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.place"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlace([NotNull] HyTekParser.PlaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.place"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlace([NotNull] HyTekParser.PlaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.jerseyNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJerseyNumber([NotNull] HyTekParser.JerseyNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.jerseyNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJerseyNumber([NotNull] HyTekParser.JerseyNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.athleteName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAthleteName([NotNull] HyTekParser.AthleteNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.athleteName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAthleteName([NotNull] HyTekParser.AthleteNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.athleteYear"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAthleteYear([NotNull] HyTekParser.AthleteYearContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.athleteYear"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAthleteYear([NotNull] HyTekParser.AthleteYearContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.schoolName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchoolName([NotNull] HyTekParser.SchoolNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.schoolName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchoolName([NotNull] HyTekParser.SchoolNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.seed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeed([NotNull] HyTekParser.SeedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.seed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeed([NotNull] HyTekParser.SeedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.time"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTime([NotNull] HyTekParser.TimeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.time"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTime([NotNull] HyTekParser.TimeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.distance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDistance([NotNull] HyTekParser.DistanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.distance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDistance([NotNull] HyTekParser.DistanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.dq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDq([NotNull] HyTekParser.DqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.dq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDq([NotNull] HyTekParser.DqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.dqReason"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDqReason([NotNull] HyTekParser.DqReasonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.dqReason"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDqReason([NotNull] HyTekParser.DqReasonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.performance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPerformance([NotNull] HyTekParser.PerformanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.performance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPerformance([NotNull] HyTekParser.PerformanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.heatNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeatNumber([NotNull] HyTekParser.HeatNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.heatNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeatNumber([NotNull] HyTekParser.HeatNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.points"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPoints([NotNull] HyTekParser.PointsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.points"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPoints([NotNull] HyTekParser.PointsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.tiebreaker"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTiebreaker([NotNull] HyTekParser.TiebreakerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.tiebreaker"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTiebreaker([NotNull] HyTekParser.TiebreakerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.hour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHour([NotNull] HyTekParser.HourContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.hour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHour([NotNull] HyTekParser.HourContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.minute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMinute([NotNull] HyTekParser.MinuteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.minute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMinute([NotNull] HyTekParser.MinuteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.second"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSecond([NotNull] HyTekParser.SecondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.second"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSecond([NotNull] HyTekParser.SecondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.decimal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimal([NotNull] HyTekParser.DecimalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.decimal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimal([NotNull] HyTekParser.DecimalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.period"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPeriod([NotNull] HyTekParser.PeriodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.period"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPeriod([NotNull] HyTekParser.PeriodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.day"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDay([NotNull] HyTekParser.DayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.day"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDay([NotNull] HyTekParser.DayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.month"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMonth([NotNull] HyTekParser.MonthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.month"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMonth([NotNull] HyTekParser.MonthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.year"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYear([NotNull] HyTekParser.YearContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.year"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYear([NotNull] HyTekParser.YearContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.date"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDate([NotNull] HyTekParser.DateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.date"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDate([NotNull] HyTekParser.DateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.clockTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClockTime([NotNull] HyTekParser.ClockTimeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.clockTime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClockTime([NotNull] HyTekParser.ClockTimeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.foot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFoot([NotNull] HyTekParser.FootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.foot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFoot([NotNull] HyTekParser.FootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.inch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInch([NotNull] HyTekParser.InchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.inch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInch([NotNull] HyTekParser.InchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] HyTekParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] HyTekParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HyTekParser.words"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWords([NotNull] HyTekParser.WordsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HyTekParser.words"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWords([NotNull] HyTekParser.WordsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
