INSERT INTO [dbo].[Conference] ([Name]) VALUES ('None');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Columbus City League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Northeastern Buckeye Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Mid-State League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Eastern Cincinnati Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Shelby County Athletic League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Cross County Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Green Meadows Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Blanchard Valley Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Greater Catholic League Co-Ed Division');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Northwest Ohio Athletic League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('All-American Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Southwestern Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Chagrin Valley Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('North Coast League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Greater Western Ohio Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Lake Erie League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Ohio Valley Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Southwestern Buckeye League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Central Buckeye Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Tri-Valley Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Southern Buckeye Athletic/Academic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Ohio Capital Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Central Catholic League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Northern Lakes League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Toledo City Athletic League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Northeastern Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Patriot Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Greater Cleveland Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Western Reserve Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Akron City Series');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Northern 10 Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Buckeye 8');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Pioneer Valley Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Mid-Ohio Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('East Central Ohio League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Federal League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Independent');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Toledo Area Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Ohio Heritage Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Knox Morrow Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Mid-Buckeye Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Three Rivers Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Scioto Valley Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Miami Valley Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Southern Ohio Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Inter-Valley Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Midwest Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Cleveland Senate Athletic League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Sandusky Bay Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Northwest Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Northwest Central Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Greater Miami Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Portage Trail Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Licking County League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Muskingum Valley League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Principals Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Metro Buckeye Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Cincinnati Hills League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Western Buckeye League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Mid-Ohio Christian Athletic League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Ohio Cardinal Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Dayton City League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Firelands Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Inter Tri-County League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Southwest Ohio Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Buckeye Border Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Greater Catholic League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Suburban League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Southern Hills Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Ohio Valley Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Northern Buckeye Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Great Lakes Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Cincinnati Metro Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Mahoning Valley Athletic Conference');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Putnam County League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Girls Greater Catholic League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Wayne County Athletic League');
INSERT INTO [dbo].[Conference] ([Name]) VALUES ('Midland Athletic League');